mainModule.constant("moduleConstants", {
	anonymousUserCaption: "Авторизуватись",
	authorizeSuccessCaption: "User has been authorized",
	authorizeNotSuccessCaption: "User has not been authorized",
	userNotFoundCaption: "User was not found",
	getUserSuccessCaption: "Get user success",
	getUserNotSuccessCaption: "Get user not success",
	getUsersSuccessCaption: "Get users success",
	getUsersNotSuccessCaption: "Get users no success",
	closedSessionMeesage: "Session has been closed",
	loginPath: "/login",
	settingsPath: "/settings",
	homePath: "/home",
	cooperationApplicationCreatingSuccess: "Дякуємо за виділений вами час, ми вам перетелефонуємо!",
	emptyFormValue: "не вказано",
	callFeedbackAccepted: "Ваша заявка прийнята",
	deleteTaskConfirmation: "Ви дійсно хочете видалити задачу?",
	userInfoCaption: "Інформація про користувача:",
	invalidPictureFormat: "Картинки повинні бути у форматі jpg, jpeg, png",
	pictureSizeLimitMb: 2,
	pictureSizeInvalid: "Розмір картинки повинен бути не більше {0} МБ",
	notFoundPath: "/404",
	acceptTaskConfirmation: "Ви дійсно хочете прийняти заявку?",
	deleteApplicationConfirmation: "Ви дійсно хочете видалити заявку?",
	deletingInfoSuccess: "Заявка була видалена",
	accountsPath: "/accounts",
	deleteUserConfirmation: "Ви дійсно хочете видалити користувача?",
    pageRowsCount: 5
});